import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Lock, FileText, Building2, UserCheck, HelpCircle, Phone, Mail } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50/50 py-12 sm:py-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 bg-blue-50 text-blue-700 rounded-full text-xs font-bold border border-blue-100">
            <ShieldCheck className="w-4 h-4 text-blue-600" /> Platform Policies & Legal Framework
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-gray-900 tracking-tight">
            Terms & Conditions & Privacy Policy
          </h1>
          <p className="text-sm text-gray-500 max-w-2xl mx-auto">
            Last Updated: September 2026 • Legal terms, multi-tenant security policies, and institutional usage guidelines for EduMan.
          </p>
        </div>

        {/* Policy Body */}
        <div className="bg-white rounded-3xl p-6 sm:p-10 border border-gray-200/80 shadow-xl shadow-gray-100 space-y-8 text-gray-700 text-sm leading-relaxed">
          
          {/* Section 1 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2 border-b border-gray-100 pb-2">
              <Building2 className="w-5 h-5 text-blue-600" /> 1. Institutional Registration & Account Accreditation
            </h2>
            <p>
              EduMan is an enterprise multi-tenant School Management System designed exclusively for educational institutions (primary, secondary, and tertiary schools).
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-xs text-gray-600">
              <li><strong>Registration Request:</strong> School accounts may be requested by authorized school leaders (Proprietors, Principals, or Administrators) via the landing page or contact channels.</li>
              <li><strong>Optional Initial Accreditation Documents:</strong> Submitting official government license or accreditation numbers during initial registration is optional for speed of onboarding. However, EduMan reserves the right to request proof of institutional standing at any time.</li>
              <li><strong>SuperAdmin Review:</strong> All new school registrations are reviewed and activated by EduMan SuperAdmin officers or verified via single-use invitation tokens.</li>
            </ul>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2 border-b border-gray-100 pb-2">
              <UserCheck className="w-5 h-5 text-indigo-600" /> 2. User Accounts & Invitation Code System
            </h2>
            <p>
              Individual users (Teachers, Instructors, Students, and Parents) do not register through unverified public signup forms.
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-xs text-gray-600">
              <li><strong>Vetted Onboarding:</strong> Access for Teachers, Students, and Parents is granted strictly through single-use or multi-use <strong>School Invitation Links or 8-character Display Codes</strong> (e.g. <code>EDU-STU-98X2A</code>) generated by their verified School Administrator.</li>
              <li><strong>Role-Based Security:</strong> Users are bound exclusively to their institution’s scope. School Admins are responsible for managing and revoking invitation links when staff or student status changes.</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2 border-b border-gray-100 pb-2">
              <Lock className="w-5 h-5 text-emerald-600" /> 3. Data Privacy & Multi-Tenant Isolation
            </h2>
            <p>
              EduMan maintains strict database isolation across all institutions.
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-xs text-gray-600">
              <li><strong>Ownership of Records:</strong> Each school retains full ownership of its student records, attendance logs, gradebooks, schemes of work, and financial fee statements.</li>
              <li><strong>Confidentiality:</strong> EduMan does not sell, share, or monetize school or student personal data. All data is protected under modern encryption standards.</li>
              <li><strong>Offline-First Synchronization:</strong> Offline content cached locally on client devices remains bound to authorized account credentials.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2 border-b border-gray-100 pb-2">
              <FileText className="w-5 h-5 text-amber-600" /> 4. Acceptable Platform Use & Content Guidelines
            </h2>
            <p>
              Users agree not to upload malicious software, inappropriate content, or unauthorized copyrighted materials into the EduMan Content Library, Homework Submission System, or Support Center.
            </p>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2 border-b border-gray-100 pb-2">
              <HelpCircle className="w-5 h-5 text-purple-600" /> 5. Account Suspension & Termination
            </h2>
            <p>
              EduMan reserves the right to suspend or terminate accounts in cases of fraudulent institutional claims, security violations, or material breach of these terms.
            </p>
          </section>

          {/* Contact Box */}
          <div className="mt-8 p-6 bg-gradient-to-br from-blue-50 to-indigo-50/50 rounded-2xl border border-blue-100 space-y-2 text-xs">
            <h3 className="font-bold text-gray-900 text-sm flex items-center gap-2">
              <Mail className="w-4 h-4 text-blue-600" /> Have Questions Regarding Our Terms?
            </h3>
            <p className="text-gray-600">
              For inquiries regarding platform policies, institutional accreditation, or legal compliance, contact our legal and support team:
            </p>
            <div className="pt-2 flex flex-wrap gap-4 font-semibold text-gray-800">
              <span className="flex items-center gap-1"><Phone className="w-3.5 h-3.5 text-blue-600" /> 09156457073</span>
              <span className="flex items-center gap-1"><Mail className="w-3.5 h-3.5 text-blue-600" /> supports@eduman.africa</span>
              <span>📍 Delta State, Nigeria</span>
            </div>
          </div>

        </div>

        {/* Back Link */}
        <div className="text-center pt-2">
          <Link to="/" className="text-xs font-bold text-blue-600 hover:text-blue-800 hover:underline">
            ← Return to EduMan Homepage
          </Link>
        </div>

      </div>
    </div>
  );
}
